# Demographic Research Methods and the PyCCM Library
## Computer Lab 1: An Introduction to Python for PyCCM
## Instructor: Jiani Yan
## Date: October 27th, 2025
---

In this class, we are going to learn about the basic building blocks of Python. We will try to finish both sections in the class, but it might be that Section 2 should be done as a 'class homework'. Section 1 will be live coded. Solutions for Section 2 will either be presented at the start of the second day, or at the end of the class, time permitting.

## 1. Section 1: To be taught by JY
---

In [2]:
from pathlib import Path
lab = Path.cwd().parent/'files'

print(Path.cwd())
print(lab)


/Users/valler/Python/PyCCM/course/labs/questions
/Users/valler/Python/PyCCM/course/labs/files


#### 1.1 Whats a float? Whats an int?

In [3]:
# <Your answer goes here>
population = 100000
print(type(population))

<class 'int'>


In [4]:
birth_rate=2.5
print(type(birth_rate))

<class 'float'>


#### 1.1.1 What common arithmetic operators can we use on them?

In [5]:
# <Your answer goes here>
print(10+5)
print(10-5)
print(10*5)
print(10/5)
print(10**2)

15
5
50
2.0
100


#### 1.1.2. Is 2/1 an int or a float? Why?

In [6]:
# <Your answer goes here>
result = 2/1

In [7]:
print(result)        # 2.0
print(type(result))

2.0
<class 'float'>


### 1.2 How do we print things?

In [9]:
# <Your answer goes here>
words="colombia"
print("Hola",words)

Hola colombia


### 1.3 How do we assign things?

In [10]:
# <Your answer goes here>
words

'colombia'

### 1.4 What's a character set?

In [12]:
# <Your answer goes here>
emoji = "☺️"
emoji

'☺️'

### 1.5 What's a string?

In [7]:
# <Your answer goes here>

#### 1.5.1 How do we slice strings?

In [14]:
age_range = "25-29"

In [15]:
# <Your answer goes here>
first_part = age_range[0:2]
second_part = age_range[3:5]

In [17]:
age_range[3:4]

'2'

In [16]:
print(f"Ages {first_part} to {second_part}")

Ages 25 to 29


In [21]:
age_range[-1]

'9'

In [22]:
age_range[:2]

'25'

#### 1.5.2 What are some common string methods?

In [23]:
country = "  Mexico  "

In [24]:
# <Your answer goes here>
country.strip() # removes all the spaces

'Mexico'

In [25]:
country.upper()

'  MEXICO  '

In [26]:
country.lower()

'  mexico  '

In [29]:
country.replace("Mexico",'Colombia').replace(' ','')

'Colombia'

In [33]:
'Mexico"'

'Mexico"'

#### 1.5.3 How do we join and split strings?



In [34]:
ages =  "0-14,15-64,65+"

In [35]:
# <Your answer goes here>
ages.split(",")

['0-14', '15-64', '65+']

In [40]:
lst= ['1','2','3'] 
';'.join(lst)

'1;2;3'

### 1.6. What's a collection?

In [51]:
# <Your answer goes here>
# list example 
lst = [1,2,3,5] 
lst

[1, 2, 3, 5]

In [48]:
lst[-2]

3

In [49]:
len(lst)

4

In [52]:
sum(lst)

11

In [53]:
max(lst)

5

In [54]:
min(lst)

1

In [43]:
# tuple example 
coordinates = (40.7128, -74.0060)


In [ ]:
import numpy as np

In [58]:
min(coordinates)

-74.006

In [55]:
coordinates[0]

40.7128

In [61]:
# dictionary 
rates = {'birth': 12.5,
         'death':8.3,
        "words":"1bajasey",
        "list":[1,2,5]}

In [62]:
rates['list'] # accessing the value paired with the key

[1, 2, 5]

In [63]:
rates.keys()

dict_keys(['birth', 'death', 'words', 'list'])

In [64]:
rates.values()

dict_values([12.5, 8.3, '1bajasey', [1, 2, 5]])

#### 1.6.1 What's a list?

In [12]:
# <Your answer goes here>



#### 1.6.2 What's a dictionary?

In [13]:
# <Your answer goes here>

#### 1.6.3 What's a tuple?

In [14]:
# <Your answer goes here>

#### 1.6.4 How do these things differ?

In [15]:
# <Your answer goes here>

### 1.7. What's an iteration?

In [69]:
# <Your answer goes here>
populations = [100,200,300] 
for pop in populations:
    print(f"original population: {pop}")
    print(pop+500)
    for a in ['1','2']:
        print(a)

original population: 100
600
1
2
original population: 200
700
1
2
original population: 300
800
1
2


#### 1.7.1. How does indentation in Python work?

In [17]:
# <Your answer goes here>

#### 1.7.2 How can we iterate over a collection?

In [18]:
# <Your answer goes here>


#### 1.7.3 How can we iterate over multiple collections simultaneously?


In [70]:
countries = ['USA', 'Canada', 'Mexico']
populations = [331000000, 38000000, 128000000]

In [75]:
# <Your answer goes here>
for country,pop in zip(countries,populations):
    print(f"{country}: {pop}")

USA: 331000000
Canada: 38000000
Mexico: 128000000


### 1.8. What's Boolean Logic?

In [76]:
# <Your answer goes here>
birth_rate = 12.5 
death_rate = 8.3 
is_growing = birth_rate>death_rate

In [77]:
print(f"Population growing: {is_growing}") 

Population growing: True


In [78]:
print(5>3)

True


In [79]:
print(5>6)

False


In [80]:
print(5!=3)

True


#### 1.8.1 How can we control flow in Python?

In [83]:
# if-else: choose between options
age = 13

if age > 18:
    print("Adult")
else:
    print('Minor')

Minor


In [84]:
# if-elif-else: multiple conditions
pop = 100 
if pop > 200:
    print("large village")
elif pop<100:
    print("small village")
else: 
    print("medium village")

medium village


In [85]:
# One-line version
age = 20
status = "Adult" if age>=18 else "Minor"
print(status)

Adult


#### 1.8.2 How can we combine iteration and control in Python?

In [88]:
# Combine for loops with if statements
population = [100,200,300] 

for pop in population: 
    if pop > 200:
        print("big village")
    elif pop < 100:
        print("small village")
    else:
        print("medium village")

medium village
medium village
big village


In [89]:
# Process only certain items
ages= [2,5,35,57,75] 

for age in ages:
    if 15 <= age <57:
        print(f"age {age} is working age")
        

age 35 is working age


#### 1.8.3 How do while loops work?

In [92]:
# <Your answer goes here>
population = 100 
year = 0 

while population < 200:
    population = population  *  1.02
    year +=1 # year = year+1 
    
print(f"population will be doubled in {year} years")

population will be doubled in 36 years


In [95]:
population=100
population*=1.02
population

102.0

In [93]:
print(f"Population doubled in {year} years")

Population doubled in 36 years


#### 1.8.4 How can we continue if a condition is met?

In [97]:
for i in range(5):
    print(i)

0
1
2
3
4


In [98]:
# <Your answer goes here>

for i in range(5):
    if i == 2: 
        continue 
    print(i) 

0
1
3
4


#### 1.8.5 How can we break out of a loop at a specific point in time?

In [106]:
# <Your answer goes here>
numbers = [1,3,5,7,8]
for ind,num in enumerate(numbers):
    if num == 7:
        print(f"Found 7! at {ind}")
        break
    print(f"checking {num}, {ind} th element..")

checking 1, 0 th element..
checking 3, 1 th element..
checking 5, 2 th element..
Found 7! at 3


### 1.9. How can we handle errors with 'try' and 'except'?

In [107]:
# <Your answer goes here>

try:
    result = 10/ 0
except:
    print("skipping: zero division")
    result = 0 

skipping: zero division


In [110]:
populations = [100,0,250,0]
deaths = [90,100,20,30]

for pop, death in zip(populations, deaths):
    try:
        rate = (death/pop)
        print(f"rate {rate}")
    except:
        print("skipping: zero population")

rate 0.9
skipping: zero population
rate 0.08
skipping: zero population


### 1.10. How can we define a function?

In [116]:
# <Your answer goes here>
def greet_person(name,age):
    print("Hi, I'm", name)
    print(f"I'm {age} years-old")

In [119]:
greet_person("Jiani",33)

Hi, I'm Jiani
I'm 33 years-old


#### 1.10.1 How can we return something from it?

In [125]:
# <Your answer goes here>
def calculate_rate(deaths, population,per=1000):
    return (deaths/population)*per

In [126]:
result = calculate_rate(839,1000,10000)
print(result) 

8390.0


In [127]:
calculate_rate(839,1000,500)

419.5

In [128]:
calculate_rate(839,1000)

839.0

#### 1.10.2 What's the difference between a local and a global variable?

In [131]:
# <Your answer goes here>
population = 100 

def check_var():
    population = 200
    print(f"population is {population}")

In [138]:
def caculate_rate():
    death_count= 830
    return death_count/population 

In [135]:
caculate_rate()

8.3

In [139]:
death_count 

NameError: name 'death_count' is not defined

In [133]:
check_var()

population is 200


In [132]:
population

100

#### 1.11.1 How do we read files in Python

In [140]:
lab

PosixPath('/Users/valler/Python/PyCCM/course/labs/files')

In [141]:
# <Your answer goes here>
with open(lab/"example_text.txt","r") as file:
    for line in file:
        print(line.strip())

This is an example text file
It contains multiple rows
I hope you are enjoying the python course so far!
Bono oculto: si ves esta frase, ¡tomemos un descanso de 5 minutos!


#### 1.11.2 How do we write files in Python

In [142]:
# <Your answer goes here>
with open(lab/'example_2.txt',"w") as file:
    file.write("Hola")

### 1.12. How do we import libraries, like numpy?

In [143]:
# <Your answer goes here>
import numpy as np 

In [144]:
mean([1,2,3])

NameError: name 'mean' is not defined

In [146]:
np.mean([1,2,3])

np.float64(2.0)

### 1.12.1 What's a numpy array? why's it good?

In [151]:
# <Your answer goes here>
populations = np.array([100,200,300])
print(type(populations))

<class 'numpy.ndarray'>


In [152]:
doubled_population = population*2
print(doubled_population)

200


In [154]:
[100,200,300]*2

[100, 200, 300, 100, 200, 300]

In [155]:
populations.mean()

np.float64(200.0)

In [156]:
populations.sum()

np.int64(600)

### 1.12.2 How can we do some simple arithmetic operation with numpy?

In [157]:
# <Your answer goes here>
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])


In [158]:
print(a+b)

[11 22 33 44]


In [164]:
print(a+b)
print(a*b)

[11 22 33 44]
[ 10  40  90 160]


In [161]:
print(a**2)

[ 1  4  9 16]


### 1.13. What's a dataframe?

In [35]:
# <Your answer goes here>

#### 1.13.1 How can we create an arbitrary dataframe?

In [36]:
# <Your answer goes here>

#### 1.13.2 How can we populate a dataframe from a numpy array?

In [37]:
# <Your answer goes here>

#### 1.13.3 How can we filter dataframes?

In [ ]:
import pandas as pd
data = {
    'country': ['USA', 'Canada', 'Mexico', 'Brazil'],
    'population': [331000000, 38000000, 128000000, 212000000],
    'birth_rate': [12.5, 10.9, 17.6, 14.6]
}
data = pd.DataFrame(data)

In [38]:
# <Your answer goes here>

#### 1.13.4 How can we sort them?

In [ ]:
data = {
    'country': ['Brazil', 'USA', 'Mexico', 'Canada'],
    'population': [212000000, 331000000, 128000000, 38000000]
}
data = pd.DataFrame(data)

In [39]:
# <Your answer goes here>

#### 1.13.5 How can we read files from disk with pandas?

In [40]:
# <Your answer goes here>

#### 1.13.6 How can we write files to disk with pandas?

In [41]:
# <Your answer goes here>

### 1.14. How can we import matplotlib?

In [42]:
# <Your answer goes here>

#### 1.14.1 How can we plot a numpy array with matplotlib?

In [ ]:
years = np.array([2015, 2016, 2017, 2018, 2019, 2020])
population = np.array([1000000, 1020000, 1041000, 1062000, 1084000, 1106000])

In [43]:
# <Your answer goes here>

#### 1.14.2 How can we plot a pandas dataframe?

In [ ]:
data = {
    'year': [2015, 2016, 2017, 2018, 2019, 2020],
    'births': [130000, 132000, 128000, 126000, 124000, 122000],
    'deaths': [82000, 84000, 86000, 88000, 90000, 92000]
}
df = pd.DataFrame(data)

In [44]:
# <Your answer goes here>

#### 1.15. How can we import functions from local modules?

In [45]:
# <Your answer goes here>

---
## 2. Section 2: Class questions -- either to be done in class, or as optional homework
---

### Q1. Replicate the exponential growth module seen in the lectures.

i. Create three numpy arrays with a starting value.

ii. Sequentially multiple them by the exponent.

iii. Plot the three different values.

In [46]:
# <Your answer goes here>

### Question 2.

i. Load in the conteos.rds file hosted in this repository (`./data`) as a pandas dataframe. Ideally, use the data_loaders module.

ii. Filter the dataframe for total national data, EEVV, and the year 2018.

iii. Drop values where age is NaN.

iv. Add the population count for males to females.

v. Add the death counts for males to females.

vi. Divide death counts by the population values.

vii. PLot this -- death rates -- ('m_x') value. 

viiii. Repeat step vii., but instead with logged death rates.